// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: calendar.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Sous-ensemble minimal de gdi_smart_proto.proto + gdi_calendar_service.proto
/// (Gadgetbridge, AGPL — voir garmin-bridge). On ne porte QUE le service
/// calendrier (champ 1 du message Smart) : la montre Venu 2 émet un
/// CalendarServiceRequest pendant une session GFDI, on répond un
/// CalendarServiceResponse. Numéros de champ IDENTIQUES à l'upstream — le fil
/// est compatible octet-pour-octet.
///
/// Généré vers all/GFDI/calendar.pb.swift :
///   protoc --swift_out=all/all/GFDI --proto_path=all/proto all/proto/calendar.proto

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Enveloppe Smart réduite au seul champ calendrier (champ 1). Les autres
/// services (http=2, core=13, …) sont volontairement absents : proto ignore les
/// champs inconnus en décodage, et on n'encode que ce champ en réponse.
nonisolated struct GCalSmart: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var calendarService: GCalCalendarService {
    get {_calendarService ?? GCalCalendarService()}
    set {_calendarService = newValue}
  }
  /// Returns true if `calendarService` has been explicitly set.
  var hasCalendarService: Bool {self._calendarService != nil}
  /// Clears the value of `calendarService`. Subsequent reads from it will return its default value.
  mutating func clearCalendarService() {self._calendarService = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _calendarService: GCalCalendarService? = nil
}

nonisolated struct GCalCalendarService: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var calendarRequest: GCalCalendarService.CalendarServiceRequest {
    get {_calendarRequest ?? GCalCalendarService.CalendarServiceRequest()}
    set {_calendarRequest = newValue}
  }
  /// Returns true if `calendarRequest` has been explicitly set.
  var hasCalendarRequest: Bool {self._calendarRequest != nil}
  /// Clears the value of `calendarRequest`. Subsequent reads from it will return its default value.
  mutating func clearCalendarRequest() {self._calendarRequest = nil}

  var calendarResponse: GCalCalendarService.CalendarServiceResponse {
    get {_calendarResponse ?? GCalCalendarService.CalendarServiceResponse()}
    set {_calendarResponse = newValue}
  }
  /// Returns true if `calendarResponse` has been explicitly set.
  var hasCalendarResponse: Bool {self._calendarResponse != nil}
  /// Clears the value of `calendarResponse`. Subsequent reads from it will return its default value.
  mutating func clearCalendarResponse() {self._calendarResponse = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated struct CalendarServiceRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var begin: UInt32 {
      get {_begin ?? 0}
      set {_begin = newValue}
    }
    /// Returns true if `begin` has been explicitly set.
    var hasBegin: Bool {self._begin != nil}
    /// Clears the value of `begin`. Subsequent reads from it will return its default value.
    mutating func clearBegin() {self._begin = nil}

    var end: UInt32 {
      get {_end ?? 0}
      set {_end = newValue}
    }
    /// Returns true if `end` has been explicitly set.
    var hasEnd: Bool {self._end != nil}
    /// Clears the value of `end`. Subsequent reads from it will return its default value.
    mutating func clearEnd() {self._end = nil}

    var includeOrganizer: Bool {
      get {_includeOrganizer ?? false}
      set {_includeOrganizer = newValue}
    }
    /// Returns true if `includeOrganizer` has been explicitly set.
    var hasIncludeOrganizer: Bool {self._includeOrganizer != nil}
    /// Clears the value of `includeOrganizer`. Subsequent reads from it will return its default value.
    mutating func clearIncludeOrganizer() {self._includeOrganizer = nil}

    var includeTitle: Bool {
      get {_includeTitle ?? true}
      set {_includeTitle = newValue}
    }
    /// Returns true if `includeTitle` has been explicitly set.
    var hasIncludeTitle: Bool {self._includeTitle != nil}
    /// Clears the value of `includeTitle`. Subsequent reads from it will return its default value.
    mutating func clearIncludeTitle() {self._includeTitle = nil}

    var includeLocation: Bool {
      get {_includeLocation ?? true}
      set {_includeLocation = newValue}
    }
    /// Returns true if `includeLocation` has been explicitly set.
    var hasIncludeLocation: Bool {self._includeLocation != nil}
    /// Clears the value of `includeLocation`. Subsequent reads from it will return its default value.
    mutating func clearIncludeLocation() {self._includeLocation = nil}

    var includeDescription: Bool {
      get {_includeDescription ?? false}
      set {_includeDescription = newValue}
    }
    /// Returns true if `includeDescription` has been explicitly set.
    var hasIncludeDescription: Bool {self._includeDescription != nil}
    /// Clears the value of `includeDescription`. Subsequent reads from it will return its default value.
    mutating func clearIncludeDescription() {self._includeDescription = nil}

    var includeStartDate: Bool {
      get {_includeStartDate ?? true}
      set {_includeStartDate = newValue}
    }
    /// Returns true if `includeStartDate` has been explicitly set.
    var hasIncludeStartDate: Bool {self._includeStartDate != nil}
    /// Clears the value of `includeStartDate`. Subsequent reads from it will return its default value.
    mutating func clearIncludeStartDate() {self._includeStartDate = nil}

    var includeEndDate: Bool {
      get {_includeEndDate ?? false}
      set {_includeEndDate = newValue}
    }
    /// Returns true if `includeEndDate` has been explicitly set.
    var hasIncludeEndDate: Bool {self._includeEndDate != nil}
    /// Clears the value of `includeEndDate`. Subsequent reads from it will return its default value.
    mutating func clearIncludeEndDate() {self._includeEndDate = nil}

    var includeAllDay: Bool {
      get {_includeAllDay ?? false}
      set {_includeAllDay = newValue}
    }
    /// Returns true if `includeAllDay` has been explicitly set.
    var hasIncludeAllDay: Bool {self._includeAllDay != nil}
    /// Clears the value of `includeAllDay`. Subsequent reads from it will return its default value.
    mutating func clearIncludeAllDay() {self._includeAllDay = nil}

    var maxOrganizerLength: UInt32 {
      get {_maxOrganizerLength ?? 0}
      set {_maxOrganizerLength = newValue}
    }
    /// Returns true if `maxOrganizerLength` has been explicitly set.
    var hasMaxOrganizerLength: Bool {self._maxOrganizerLength != nil}
    /// Clears the value of `maxOrganizerLength`. Subsequent reads from it will return its default value.
    mutating func clearMaxOrganizerLength() {self._maxOrganizerLength = nil}

    var maxTitleLength: UInt32 {
      get {_maxTitleLength ?? 0}
      set {_maxTitleLength = newValue}
    }
    /// Returns true if `maxTitleLength` has been explicitly set.
    var hasMaxTitleLength: Bool {self._maxTitleLength != nil}
    /// Clears the value of `maxTitleLength`. Subsequent reads from it will return its default value.
    mutating func clearMaxTitleLength() {self._maxTitleLength = nil}

    var maxLocationLength: UInt32 {
      get {_maxLocationLength ?? 0}
      set {_maxLocationLength = newValue}
    }
    /// Returns true if `maxLocationLength` has been explicitly set.
    var hasMaxLocationLength: Bool {self._maxLocationLength != nil}
    /// Clears the value of `maxLocationLength`. Subsequent reads from it will return its default value.
    mutating func clearMaxLocationLength() {self._maxLocationLength = nil}

    var maxDescriptionLength: UInt32 {
      get {_maxDescriptionLength ?? 0}
      set {_maxDescriptionLength = newValue}
    }
    /// Returns true if `maxDescriptionLength` has been explicitly set.
    var hasMaxDescriptionLength: Bool {self._maxDescriptionLength != nil}
    /// Clears the value of `maxDescriptionLength`. Subsequent reads from it will return its default value.
    mutating func clearMaxDescriptionLength() {self._maxDescriptionLength = nil}

    var maxEvents: UInt32 {
      get {_maxEvents ?? 0}
      set {_maxEvents = newValue}
    }
    /// Returns true if `maxEvents` has been explicitly set.
    var hasMaxEvents: Bool {self._maxEvents != nil}
    /// Clears the value of `maxEvents`. Subsequent reads from it will return its default value.
    mutating func clearMaxEvents() {self._maxEvents = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _begin: UInt32? = nil
    fileprivate var _end: UInt32? = nil
    fileprivate var _includeOrganizer: Bool? = nil
    fileprivate var _includeTitle: Bool? = nil
    fileprivate var _includeLocation: Bool? = nil
    fileprivate var _includeDescription: Bool? = nil
    fileprivate var _includeStartDate: Bool? = nil
    fileprivate var _includeEndDate: Bool? = nil
    fileprivate var _includeAllDay: Bool? = nil
    fileprivate var _maxOrganizerLength: UInt32? = nil
    fileprivate var _maxTitleLength: UInt32? = nil
    fileprivate var _maxLocationLength: UInt32? = nil
    fileprivate var _maxDescriptionLength: UInt32? = nil
    fileprivate var _maxEvents: UInt32? = nil
  }

  nonisolated struct CalendarServiceResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var status: GCalCalendarService.CalendarServiceResponse.ResponseStatus {
      get {_status ?? .unknownResponseStatus}
      set {_status = newValue}
    }
    /// Returns true if `status` has been explicitly set.
    var hasStatus: Bool {self._status != nil}
    /// Clears the value of `status`. Subsequent reads from it will return its default value.
    mutating func clearStatus() {self._status = nil}

    var calendarEvent: [GCalCalendarService.CalendarEvent] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    nonisolated enum ResponseStatus: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
      case unknownResponseStatus = 0
      case ok = 1
      case invalidDateRange = 2

      init() {
        self = .unknownResponseStatus
      }

    }

    init() {}

    fileprivate var _status: GCalCalendarService.CalendarServiceResponse.ResponseStatus? = nil
  }

  nonisolated struct CalendarEvent: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var organizer: String {
      get {_organizer ?? String()}
      set {_organizer = newValue}
    }
    /// Returns true if `organizer` has been explicitly set.
    var hasOrganizer: Bool {self._organizer != nil}
    /// Clears the value of `organizer`. Subsequent reads from it will return its default value.
    mutating func clearOrganizer() {self._organizer = nil}

    var title: String {
      get {_title ?? String()}
      set {_title = newValue}
    }
    /// Returns true if `title` has been explicitly set.
    var hasTitle: Bool {self._title != nil}
    /// Clears the value of `title`. Subsequent reads from it will return its default value.
    mutating func clearTitle() {self._title = nil}

    var location: String {
      get {_location ?? String()}
      set {_location = newValue}
    }
    /// Returns true if `location` has been explicitly set.
    var hasLocation: Bool {self._location != nil}
    /// Clears the value of `location`. Subsequent reads from it will return its default value.
    mutating func clearLocation() {self._location = nil}

    var description_p: String {
      get {_description_p ?? String()}
      set {_description_p = newValue}
    }
    /// Returns true if `description_p` has been explicitly set.
    var hasDescription_p: Bool {self._description_p != nil}
    /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
    mutating func clearDescription_p() {self._description_p = nil}

    var startDate: UInt32 {
      get {_startDate ?? 0}
      set {_startDate = newValue}
    }
    /// Returns true if `startDate` has been explicitly set.
    var hasStartDate: Bool {self._startDate != nil}
    /// Clears the value of `startDate`. Subsequent reads from it will return its default value.
    mutating func clearStartDate() {self._startDate = nil}

    var endDate: UInt32 {
      get {_endDate ?? 0}
      set {_endDate = newValue}
    }
    /// Returns true if `endDate` has been explicitly set.
    var hasEndDate: Bool {self._endDate != nil}
    /// Clears the value of `endDate`. Subsequent reads from it will return its default value.
    mutating func clearEndDate() {self._endDate = nil}

    var allDay: Bool {
      get {_allDay ?? false}
      set {_allDay = newValue}
    }
    /// Returns true if `allDay` has been explicitly set.
    var hasAllDay: Bool {self._allDay != nil}
    /// Clears the value of `allDay`. Subsequent reads from it will return its default value.
    mutating func clearAllDay() {self._allDay = nil}

    var reminderTimeInSecs: [UInt32] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _organizer: String? = nil
    fileprivate var _title: String? = nil
    fileprivate var _location: String? = nil
    fileprivate var _description_p: String? = nil
    fileprivate var _startDate: UInt32? = nil
    fileprivate var _endDate: UInt32? = nil
    fileprivate var _allDay: Bool? = nil
  }

  init() {}

  fileprivate var _calendarRequest: GCalCalendarService.CalendarServiceRequest? = nil
  fileprivate var _calendarResponse: GCalCalendarService.CalendarServiceResponse? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "bridgeconnect.calendar"

nonisolated extension GCalSmart: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Smart"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}calendar_service\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._calendarService) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._calendarService {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GCalSmart, rhs: GCalSmart) -> Bool {
    if lhs._calendarService != rhs._calendarService {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension GCalCalendarService: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CalendarService"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}calendar_request\0\u{3}calendar_response\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._calendarRequest) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._calendarResponse) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._calendarRequest {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._calendarResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GCalCalendarService, rhs: GCalCalendarService) -> Bool {
    if lhs._calendarRequest != rhs._calendarRequest {return false}
    if lhs._calendarResponse != rhs._calendarResponse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension GCalCalendarService.CalendarServiceRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = GCalCalendarService.protoMessageName + ".CalendarServiceRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}begin\0\u{1}end\0\u{3}include_organizer\0\u{3}include_title\0\u{3}include_location\0\u{3}include_description\0\u{3}include_start_date\0\u{3}include_end_date\0\u{3}include_all_day\0\u{3}max_organizer_length\0\u{3}max_title_length\0\u{3}max_location_length\0\u{3}max_description_length\0\u{3}max_events\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._begin) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._end) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._includeOrganizer) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._includeTitle) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._includeLocation) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._includeDescription) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._includeStartDate) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self._includeEndDate) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._includeAllDay) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self._maxOrganizerLength) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self._maxTitleLength) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self._maxLocationLength) }()
      case 13: try { try decoder.decodeSingularUInt32Field(value: &self._maxDescriptionLength) }()
      case 14: try { try decoder.decodeSingularUInt32Field(value: &self._maxEvents) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._begin {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._end {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._includeOrganizer {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._includeTitle {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._includeLocation {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._includeDescription {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._includeStartDate {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._includeEndDate {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._includeAllDay {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._maxOrganizerLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._maxTitleLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._maxLocationLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._maxDescriptionLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._maxEvents {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 14)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GCalCalendarService.CalendarServiceRequest, rhs: GCalCalendarService.CalendarServiceRequest) -> Bool {
    if lhs._begin != rhs._begin {return false}
    if lhs._end != rhs._end {return false}
    if lhs._includeOrganizer != rhs._includeOrganizer {return false}
    if lhs._includeTitle != rhs._includeTitle {return false}
    if lhs._includeLocation != rhs._includeLocation {return false}
    if lhs._includeDescription != rhs._includeDescription {return false}
    if lhs._includeStartDate != rhs._includeStartDate {return false}
    if lhs._includeEndDate != rhs._includeEndDate {return false}
    if lhs._includeAllDay != rhs._includeAllDay {return false}
    if lhs._maxOrganizerLength != rhs._maxOrganizerLength {return false}
    if lhs._maxTitleLength != rhs._maxTitleLength {return false}
    if lhs._maxLocationLength != rhs._maxLocationLength {return false}
    if lhs._maxDescriptionLength != rhs._maxDescriptionLength {return false}
    if lhs._maxEvents != rhs._maxEvents {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension GCalCalendarService.CalendarServiceResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = GCalCalendarService.protoMessageName + ".CalendarServiceResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{3}calendar_event\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._status) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.calendarEvent) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._status {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    if !self.calendarEvent.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.calendarEvent, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GCalCalendarService.CalendarServiceResponse, rhs: GCalCalendarService.CalendarServiceResponse) -> Bool {
    if lhs._status != rhs._status {return false}
    if lhs.calendarEvent != rhs.calendarEvent {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension GCalCalendarService.CalendarServiceResponse.ResponseStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN_RESPONSE_STATUS\0\u{1}OK\0\u{1}INVALID_DATE_RANGE\0")
}

nonisolated extension GCalCalendarService.CalendarEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = GCalCalendarService.protoMessageName + ".CalendarEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}organizer\0\u{1}title\0\u{1}location\0\u{1}description\0\u{3}start_date\0\u{3}end_date\0\u{3}all_day\0\u{3}reminder_time_in_secs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._organizer) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._location) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._startDate) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._endDate) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._allDay) }()
      case 8: try { try decoder.decodeRepeatedUInt32Field(value: &self.reminderTimeInSecs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._organizer {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._location {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._startDate {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._endDate {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._allDay {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    if !self.reminderTimeInSecs.isEmpty {
      try visitor.visitRepeatedUInt32Field(value: self.reminderTimeInSecs, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GCalCalendarService.CalendarEvent, rhs: GCalCalendarService.CalendarEvent) -> Bool {
    if lhs._organizer != rhs._organizer {return false}
    if lhs._title != rhs._title {return false}
    if lhs._location != rhs._location {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._startDate != rhs._startDate {return false}
    if lhs._endDate != rhs._endDate {return false}
    if lhs._allDay != rhs._allDay {return false}
    if lhs.reminderTimeInSecs != rhs.reminderTimeInSecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
